//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Planor.Properties
{
    using System;
    using System.Resources;

    internal class Resources
    {
        private static ResourceManager resourceMan = new ResourceManager("Planor.Properties.Resources", typeof(Resources).Assembly);
        private static CultureInfo resourceCulture;

        internal static Bitmap acntürk_logo => (Bitmap)resourceMan.GetObject("acntürk-logo", resourceCulture);
        internal static Bitmap ak_logo => (Bitmap)resourceMan.GetObject("ak-logo", resourceCulture);
        internal static Bitmap allianz_logo => (Bitmap)resourceMan.GetObject("allianz-logo", resourceCulture);
        internal static Bitmap ana_logo => (Bitmap)resourceMan.GetObject("ana-logo", resourceCulture);
        internal static Bitmap anadolu_logo => (Bitmap)resourceMan.GetObject("anadolu-logo", resourceCulture);
        internal static Bitmap ankara_logo => (Bitmap)resourceMan.GetObject("ankara-logo", resourceCulture);
        internal static Bitmap appicon64 => (Bitmap)resourceMan.GetObject("appicon64", resourceCulture);
        internal static Bitmap arex_logo => (Bitmap)resourceMan.GetObject("arex-logo", resourceCulture);
        internal static Bitmap atlas_logo => (Bitmap)resourceMan.GetObject("atlas-logo", resourceCulture);
        internal static Bitmap avatar => (Bitmap)resourceMan.GetObject("avatar", resourceCulture);
        internal static Bitmap avatargry => (Bitmap)resourceMan.GetObject("avatargry", resourceCulture);
        internal static Bitmap aveon_logo => (Bitmap)resourceMan.GetObject("aveon-logo", resourceCulture);
        internal static Bitmap axa_logo => (Bitmap)resourceMan.GetObject("axa-logo", resourceCulture);
        internal static Bitmap axatek_logo => (Bitmap)resourceMan.GetObject("axatek-logo", resourceCulture);
        internal static Bitmap banner_orta => (Bitmap)resourceMan.GetObject("banner-orta", resourceCulture);
        internal static Bitmap banner_sag => (Bitmap)resourceMan.GetObject("banner-sag", resourceCulture);
        internal static Bitmap banner_sag1 => (Bitmap)resourceMan.GetObject("banner-sag1", resourceCulture);
        internal static Bitmap banner_sol => (Bitmap)resourceMan.GetObject("banner-sol", resourceCulture);
        internal static Bitmap bereket_logo => (Bitmap)resourceMan.GetObject("bereket-logo", resourceCulture);
        internal static Bitmap cm_logo_kopya => (Bitmap)resourceMan.GetObject("cm logo kopya", resourceCulture);
        internal static Bitmap corpus_logo => (Bitmap)resourceMan.GetObject("corpus-logo", resourceCulture);
        internal static Bitmap corpus_logo1 => (Bitmap)resourceMan.GetObject("corpus-logo1", resourceCulture);
        internal static Bitmap demir_logo => (Bitmap)resourceMan.GetObject("demir-logo", resourceCulture);
        internal static Bitmap doga_logo => (Bitmap)resourceMan.GetObject("doga-logo", resourceCulture);
        internal static Bitmap dubai_logo => (Bitmap)resourceMan.GetObject("dubai-logo", resourceCulture);
        internal static Bitmap ethica_logo => (Bitmap)resourceMan.GetObject
